version: '2'
services:
  # PHP
  phpfpm:
    restart: always
    build: php-fpm
    volumes:
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
      - ./log/php-fpm:/var/log/php-fpm

  # Nginx
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - "80:80"
    links:
      - phpfpm:phpfpm
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      - ./log/nginx:/var/log/nginx
